version: "3.9"
services:
  web:
    build: 
        context: .
        dockerfile: web_src/Dockerfile 
    restart: unless-stopped
    ports:
      - target: 8000
        published: 9157
    depends_on:
     - database
     - renderer
    env_file:
      - CONFIG.env

  renderer:
    build: 
        context: .
        dockerfile: renderer_src/Dockerfile
    restart: unless-stopped
    depends_on:
     - broker
     - database
    tmpfs: /build
    env_file:
      - CONFIG.env

  broker:
    image: rabbitmq:3.8.14
    restart: unless-stopped
    env_file:
      - CONFIG.env

  database:
    image: tobi312/rpi-mariadb:10.5-alpine
    restart: unless-stopped
    volumes:
      - /var/lib/mysql
      - ./mariadb_config:/etc/mysql/conf.d
    env_file:
      - CONFIG.env
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
